### PR TITLE
Emit a chainChanged event after successfully switching chains

### PR DESCRIPTION
**Pull request by 0xDaedalus**
### To Test

- Connect to https://wallet.polygon.technology/bridge/
- Switch back and forth between polygon and ethereum using the in-app switcher
- The dapp should detect the changes and properly switch the text to Polygon / Ethereum - respectively.
- Switching the network inside of the wallet should not switch the network in the dapp.

### CODE REVIEW

**Comment by greg-nagy** [comment]
I got this when I tried to do this 

CleanShot 2022-07-08 at 17 13 10

**Comment by 0xDaedalus** [comment]
Would you mind re-testing after clearing site data on wallet.polygon.technology?  I think that you might be in a bad state from our earlier testing

**Comment by greg-nagy** [comment]
My extension was in a bad state ... sorry for that, strange though.

**Review by greg-nagy — APPROVED** [review]
love this solution!

**Pull request merged**
