### PR TITLE
Enable Background tracking of Goerli.

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Enables tracking of the Goerli network in the background.

### To Test
- [x] Load up a new extension or update an existing installation.
- [x] You should see a websocket connection to `eth-goerli.ws.alchemyapi.io` with messages going out over it.

### CODE REVIEW

**Review by mhluongo — APPROVED** [review]
:ship:

**Review by mhluongo — APPROVED** [review]
:shipit:

**Comment by mhluongo** [comment]
Resolved the merge conflict and tested again locally as well :ok_hand:

**Comment by 0xDaedalus** [comment]
tyty

**Comment by jagodarybacka** [comment]
@0xDaedalus Now Goerli is showing up in the networks chart despite not being visible on the networks switcher, looks buggy to me 🐛 Do we want to exclude it from the chart if test networks are off?
image

**Pull request merged**
