### PR TITLE
update images to new colors

### PR DESCRIPTION
**Pull request by rootial**
replace images with new ones from #1307 

@0xDaedalus @Shadowfiend @henryboldi

### CODE REVIEW

**Comment by rootial** [comment]
@henryboldi is it ok right now?

**Review by henryboldi — APPROVED** [review]
Thank you! Looks good :)

**Comment by rootial** [comment]
can we merge this pr @henryboldi ?

**Comment by henryboldi** [comment]
The checks haven't run, so I don't have permission to merge it 😬

Let me see what's going on there... I gotchu!

**Pull request merged**
