### PR TITLE
Debounce middleware call to persist the store

### PR DESCRIPTION
**Pull request by hyphenized**
Added a debounce to the redux cache middleware since `JSON.stringifying` the entire store after every dispatch is a bit expensive. Still need to test what could happen if the browser crashes before saving triggers.

## Results:

About 3.8x~ less time spent calling `encodeJSON`

### With debounce:
debounce

### Without: 
nodebounce

Note: While this improves performance, for some reason CPU still reaches 100% every so often when inspecting the background page on brave.

## To test:
- [ ] Reinstall the extension
- [ ] Start profiling the extension, add an account, time spent calling `encodeJSON` should decrease considerably

### CODE REVIEW

**Comment by mhluongo** [comment]
Don't be afraid to split separate stuff like this into even smaller independent PRs — it saves us from needing to do performance testing per commit (for example), and it saves you from a review nit around eg the manifest build slowing down the merge for an important performance improvement.

**Comment by hyphenized** [comment]
That makes sense, I'll split this up in 3 PRs. Thanks Matt!

**Comment by greg-nagy** [comment]
I won't have time to finish the testing of this PR today, but will test tomorrow

**Comment by hyphenized** [comment]
> I won't have time to finish the testing of this PR today, but will test tomorrow
Let me know if there's anything I can do to help!

**Review by greg-nagy — APPROVED** [review]
Tested and the fix works really well, ty ❤️

We will still have cpu issues in the future, but this is a huge improvement!

**Pull request merged**
