### PR TITLE
Add euler.finance to metamask impersonation list

### LINKED ISSUE #1979: Connecting to Euler from Tally Ho
Tally Ho is supported on [app.euler.finance](https://app.euler.finance), but when I connect, I get stuck in a refresh loop.

tally-on-euler

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Closes #1979 

### To Test
- [x] visit app.euler.finance
- [x] attempt to connect, connecting should work.
- [x] enable metamask alongside Tally Ho
- [ ] ensure tally ho is set as default wallet
- [ ] Remove the existing dapp connection, attempt to reconnect
- [ ] clicking on "Metamask" should connect with Tally.

### CODE REVIEW

**Comment by mhluongo** [comment]
Hmmm, I can connect to Euler as "Injected Wallet" regardless — but when I install Metamask, turn on default wallet, refresh the dApp, etc, I still get...

Screenshot from 2022-09-08 15-18-12

**Review by jagodarybacka — APPROVED** [review]
No MM + Tally is default, No MM + Tally not default -  Tally is injected wallet 
MM installed + Tally is default - Tally is Metamask option
MM installed + Tally is not default - Metamask is Metamask, no injected option - not perfect 

But I think it works as expected 🤔

**Comment by mhluongo** [comment]
Hold your horses sonny

**Comment by 0xDaedalus** [comment]
Interpreted your thumbs up as an approval

**Comment by mhluongo** [comment]
Fair enough. I still can't get this working though :grimacing:

**Comment by mhluongo** [comment]
Heisenbug :bug: but we can't dig into it now — cc @greg-nagy when you get back, there's something very odd about "use Tally Ho as default" + the order of wallet installs.

**Pull request merged**
