### PR TITLE
Ledger Plus Plus: Enable support for Ledger Nano S Plus

### LINKED ISSUE #1331: Ledger Nano plus not working / supported
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/964218696518217798

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect Ledger Nano plus

### What did not work?

Ledger is not recognized.

" I did try it with MM in the same browser and it worked. So it definitely seems an issue with Tally"

### Version

Community Edition v0.13.0

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mhluongo**
Added the Nano S Plus `productId` so newer hardware wallet users can connect with Tally Ho.

# To test

- [ ] Confirm adding a new Nano S & Nano X still work as usual on Chrome
- [ ] If you have one handy, add a Ledger Nano S Plus as a wallet. Everything should work as with other Ledger devices on Chrome.

Refs #1352, closes #1331

H/t @adrienlacombe-ledger

### CODE REVIEW

**Comment by adrienlacombe-ledger** [comment]
cc @btchip

**Comment by adrienlacombe-ledger** [comment]
cc @greweb

**Comment by jagodarybacka** [comment]
Ledger Nano S works fine ✅

**Comment by Shadowfiend** [comment]
Glorious, yes indeed!

**Pull request merged**
