### PR TITLE
Update remote devtools to @redux-devtools packages

### LINKED ISSUE #1401: Fix sqllite install issue
Currently we can't install dependencies on a new clone and run `yarn start` because of an sqllite3 install issue. 

# Info from digging
- someone stopped hosting a binary and now we fall back to a local build, and things break
- sqlite is being pulled in by the redux dev tools remotedev-server* package, and the version we're using is pretty outdated
- That package has been superseded: https://github.com/reduxjs/redux-devtools/tree/main/packages/redux-devtools-cli 
- we don't know yet if it's an easy fix or not

# Steps to reproduce
- create a new clone of the codebase
- `yarn install`
- `yarn start`

# Relevand error part (macOS)

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@16.10.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.10.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.10.0 | darwin | arm64
gyp info find Python using Python version 3.9.12 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
(node:63864) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
```

### PR DESCRIPTION
**Pull request by Shadowfiend**
These are newer and actually maintained. This also fixes an issue with
installing the older tool on macOS due to precompiled SQLite packages
not being available for the sqlite version being referenced in the
unmaintained package.

Closes #1401 .

### CODE REVIEW

**Comment by mhluongo** [comment]
A local `yarn install` looks like our `webext-redux` patch isn't applied after these changes

Screenshot from 2022-05-09 15-30-19

**Comment by Shadowfiend** [comment]
Fixed this in a hacky way. Need to poke at yarn v2 again with an eye on node-modules resolution: https://github.com/yarnpkg/yarn/issues/7572#issuecomment-753916524

**Review by mhluongo — APPROVED** [review]
Hooray!

**Comment by greg-nagy** [comment]
🎉🎉 master of yaks

**Pull request merged**
