### PR TITLE
⚛️  Merge $DOGGO token features

### PR DESCRIPTION
**Pull request by jagodarybacka**
Issue https://github.com/tallycash/extension/issues/1398
## 🔭 Background
This PR is merging all features related to $DOGGO token that were not public before. It also adds `HIDE_TOKEN_FEATURES` flag to hide them all in the interface before we are ready to release final version. These features are still in development.

## 🪲 Reviewing and testing
[This commit](https://github.com/tallycash/extension/pull/1429/commits/9591de27842ac94cb556253b92c8fb5c86c23820) was not reviewed before - it adds a feature flag. Please review that commit.
Besides that everything was already reviewed.

- test app with different feature flags (`HIDE_TOKEN_FEATURES`, `HIDE_EARN_PAGE`, `HIDE_SWAP_REWARDS`, `EARN_COMING_SOON` are relevant)
- test app on the Ethereum mainnet and on the chain fork (`USE_MAINNET_FORK` flag)

**Note**: each set of feature flags should be tested on the fresh install

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
https://media.giphy.com/media/QaSnAIwVZGeYHIrdyc/giphy.gif

**Comment by mhluongo** [comment]
Hooooooboy

**Comment by 0xDaedalus** [comment]
So - I think the acceptance criteria here is that the App works normally without the new feature flag turned on - yeah?

**Comment by jagodarybacka** [comment]
@0xDaedalus yes, with `HIDE_TOKEN_FEATURES=true` everything should be the same as on current `main`. But it would be good to test token features too 😃

**Review by 0xDaedalus — DISMISSED** [review]
Everything in the app seems to work great - lets fix conflicts and 🚢 !

**Comment by jagodarybacka** [comment]
@0xDaedalus I've fixed conflicts 😄  thank you for 2 reviews, just one more round please 🥇

**Comment by 0xDaedalus** [comment]
Ah looks like 3rd time is not the charm - we've got an unsigned commit somewhere in this PR so we can't merge:

image

**Comment by Shadowfiend** [comment]
That commit looks good. I'll forced the merge rather than slowing us down here.

**Comment by Shadowfiend** [comment]
Not a huge deal, but just for future reference--let's try and keep the feature flags positive (SHOW_*) rather than negative (HIDE_*). We've been slowly transitioning in that direction, but still have a mixed set right now 😅

**Review by Shadowfiend — APPROVED** [review]
Post merge green light here. There's an unsigned commit deep in the history but we feel good about it so we'll use the merge signature to indicate that.

**Pull request merged**
