### PR TITLE
fix: typo in variable name (idDerivationPath)

### PR DESCRIPTION
**Pull request by PabloCastellano**

### CODE REVIEW

**Comment by fernya** [comment]
Hi @PabloCastellano,

thanks for fixing this. To successfully merge this into main your commits should be signed with your GPG key. There's a guide in Github help to set that up, then you can rebase this commit to sign it with the proper GPG key with the following command:

`git rebase --exec 'git commit --amend --no-edit -n -S' -i <branch>`

**Comment by PabloCastellano** [comment]
Signed now!

**Comment by henryboldi** [comment]
Hey @PabloCastellano, https://www.youtube.com/watch?v=4V-7KnhcrbY this tutorial might come in handy

**Comment by henryboldi** [comment]
I can commit these changes signed and add @PabloCastellano as a co-author

**Comment by greg-nagy** [comment]
@henryboldi if you feel like it, that would be awesome

**Comment by henryboldi** [comment]
I've signed it with @PabloCastellano as a co-author here: https://github.com/tallycash/extension/pull/1309

**Pull request closed without merging**
