### PR TITLE
Release v0.12.4 QA/Bump - SmokeTest

### PR DESCRIPTION
**Pull request by karlmoll**
Karl's first DevBuild!

### CODE REVIEW

**Comment by Shadowfiend** [comment]
I *believe* you missed a --tags on the git push here.

**Comment by karlmoll** [comment]
> I _believe_ you missed a --tags on the git push here.

@Shadowfiend i definitely didn't explicitly add it. does the `yarn version --patch` handle the tag'ing?

**Comment by karlmoll** [comment]
and should i delete this branch and re-push with `--tags`?

**Comment by Shadowfiend** [comment]
I believe the version script does everything except push. No need to delete, just `git push --tags` should sync up the tag (and set up the draft release as a result).

**Comment by karlmoll** [comment]
@Shadowfiend for some reason `yarn version --patch` is not updating my tags. 

@henryboldi and I saw some other weird behavior with patch, but I'll need to dig into this in the morning, I think

**Comment by karlmoll** [comment]
ok, so when i cloned the repo again and ran the version patch, it set the tags correctly but it deleted the manifest.json

https://github.com/tallycash/extension/commit/e1a796969789e9fedeb5269cef65c97c74286112

**Comment by karlmoll** [comment]
[actually when i look at the tags on my machine, i'm seeing `v0.12.3-195-gb222a27d` - @henryboldi and i saw some issues with the version bump script, but were trying to bypass it for now. maybe i need to dig deeper here. ](https://github.com/tallycash/extension/issues/1278)

**Comment by greg-nagy** [comment]
Not sure if that helps but to me `yarn version` was the thing I needed. It asked me for the new version number and worked well.

**Pull request closed without merging**
