### PR TITLE
🆘 Revert ledger sign transaction container buttons

### PR DESCRIPTION
**Pull request by henryboldi**
I believe this is where that Ledger info popped up on the swap sign page

@Shadowfiend

### CODE REVIEW

**Comment by henryboldi** [comment]
Well, so there's a build error 😬

**Comment by greg-nagy** [comment]
@henryboldi https://github.com/tallycash/extension/pull/944 This is the PR that trips you over

Not sure what is a good fix here.

**Comment by henryboldi** [comment]
Reverting both didn't do the trick. I can dig in after the community call. I'll probably add better use of the feature flag instead of reverting

**Comment by greg-nagy** [comment]
Always fall forward! :)

**Review by Shadowfiend — APPROVED** [review]
Looks good :thumbsup:

**Pull request merged**
