### PR TITLE
☢️ Enriched Uranium: Parse and display ERC-20 transactions and approvals in activities

### LINKED ISSUE #588: Activity - DAI txns appearing under ETH activity
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View ETH txn history

### What did not work?

A large # of DAI txns appeared mixed in (curiously - only DAI but not txns from other tokens:

Screen Shot 2021-12-11 at 5 52 25 PM

Here's one txn that appeared in ETH activity history https://etherscan.io/tx/0xba3c8c9e51fc121f5e5c9f0861f2c773c6992da1f99a3d1e4290ecc41a581fe4

can add this read-only acct to confirm:
0x00De4B13153673BCAE2616b67bf822500d325Fc3

**... I'm wondering if the ETH-specific history is simply displaying global activity (on a spot-check, it looks like that's what may be happening)**

**Also worth noting that no other activity except ETH loads, including DAI**

Screen Shot 2021-12-11 at 6 25 29 PM

### Version

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #619: Newly received asset not appearing in assets list, only activities
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Receive ETH to use to test sending ETH

### What did not work?

Started off with 0 ETH. Sent ETH to this address.

Received,
Screen Shot 379

But not displayed, 
Screen Shot 381

Therefore there's no ETH in the balance state to allow sending. Possibly if I had waited longer, it might have eventually appeared? To get the asset to display, I had to reinstall the extension.

That said, I don't know if this issue exists if there's already at least some balance of ETH before receiving.

### Version

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #642: Incoming token send not appearing
tl;dr I sent myself $10 or Orchid. It appears in etherscan (https://etherscan.io/address/0x1cbb77b65b07403ad7f85ff073bfc29a8212219c#tokentxns) and inside MM, but not in Tally (even after 15mins+)

Screen Shot 2021-12-14 at 10 06 36 PM

Screen Shot 2021-12-14 at 10 19 38 PM

Screen Shot 2021-12-14 at 10 06 47 PM

### PR DESCRIPTION
**Pull request by mhluongo**
Screenshot from 2021-12-15 15-27-53

This PR reworks the enrichment service to

- [x] Attempt to parse all transactions as ERC-20s and categorize
- [x] Categorized non-contract transactions
- [x] Decomplect `WalletActivityListItem` a little bit
- [x] Fall back to basic display of transactions in case the enrichment service never responds

It's still not perfect! This is going to be an ongoing area of work for the wallet, forever. But it does catch ECR-20s transfers and approvals, ETH sends and receives, and fall back to contract interactions when appropriate.

Closes #588, closes #642, closes #619, though the last two will still have a delay between activity changes and balances.

### CODE REVIEW

**Review by Shadowfiend — APPROVED** [review]
Code looks good. I can't test run it, but if someone else confirms there are no regressions please merge.

**Comment by henryboldi** [comment]
I'm ok with merging this, but it does not close #588.

In the ETH asset page,
ETH asset page

In the KEEP asset page,
ETH asset page

**Review by henryboldi — APPROVED** [review]
No regressions.

great_sucess jpg

**Comment by Shadowfiend** [comment]
This makes sense. The fix remains the one I mentioned in that issue, and is in SingleAsset.tsx, which isn't touched here.

**Pull request merged**
