### PR TITLE
⚡️ Replace use of fleek's gateway to silly avoid virus scanner block

### LINKED ISSUE #1320: Virus scanner blocking token list
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/962341619133194331

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user swapped ETH to WETH

### What did not work?

The transaction was completed, but the WETH wasn't showing up.

image

User:

"One suspicious thing is that my anti-virus software detected the following url as malicious, and blocked at the beginning.
I changed the setting to allow the URL, but do you think the URL might something to do with my issue?
https://ipfs.fleek.co/ipfs/bafybeicovpqvb533alo5scf7vg34z6fjspdytbzsa2es2lz35sw3ksh2la 
"

The user re-installed the wallet and re-loaded the account. After that the WETH was showing up. I don't know if it's related to the anti-virus setting change, or just a result of reinstalling.

### Version

Community Edition v0.13.0

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by henryboldi**
> I just tried to install the Firefox extension off the tally.cash site and my antivirus (Avast) complained it needed to abort the connection to ipfs.fleek.co due to URL:Mal threat

Fixes #1320

<table>
  <tbody>
    <tr>
      <td>Before</td>
      <td>After</td>
    </tr>
    <tr>
      <td>
        scan 1
      </td>
      <td>
        scan 2
      </td>
    </tr>
  </tbody>
</table>

### CODE REVIEW

**Comment by henryboldi** [comment]
By the way, it appears that using Cloudflare's gateway is similarly block prone vs ipfs.io

cloudflare

And Comodo Valkyrie Verdict is probably more popular than SafeToOpen. Granted, I'm not sure of the validity of [VirusTotal's](https://www.virustotal.com) results.

**Review by mhluongo — APPROVED** [review]
Works locally, let's do this.

**Comment by Shadowfiend** [comment]
Tried to fetch the URL we switched to for our token list and got a 504 fwiw <_<

**Comment by mhluongo** [comment]
Interesting, [it loads for me on mobile](https://ipfs.io/ipfs/bafybeicovpqvb533alo5scf7vg34z6fjspdytbzsa2es2lz35sw3ksh2la) and the extension seemed to load assets...

**Comment by henryboldi** [comment]
Added an uptime monitor on the URL which checking every 5 min. If I get a downtime alert, I'll report back here

**Pull request merged**
