### PR TITLE
Death and Taxes: Charge fees regardless of the gated 0x API

### PR DESCRIPTION
**Pull request by mhluongo**
This change means the community multisig will go back to receiving fees for every swap.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
To be clear, this change means the multisig will for the first time get fees from dev builds :)

**Comment by mhluongo** [comment]
Yep, here for it!

**Comment by Shadowfiend** [comment]
100% same, just wanted to clarify this isn't going back to anything--only `main` builds have ever had the gated params passed along. We did briefly pass the affiliate address on all builds. 

Also forgot we upload artifacts for PRs now--those have likewise never had fees enabled.

**Review by Shadowfiend — APPROVED** [review]
Let's do it.

**Review by Shadowfiend — APPROVED** [review]
Again post-merge 😅

**Pull request merged**
