### PR TITLE
Orthogonal Networks: Don't notify dApps when extension account changes

### LINKED ISSUE #1846: Don't change network for dApps when the network is changed for the extension
* https://matrix.to/#/!WZRftnsYNnOtzOGuZy:thesis.co/$AO0U9C2IkgGRwR4m0Q8bX4K5B_LstdurVxbJi9cSR2k?via=thesis.co&via=matrix.org 
* https://github.com/tallycash/extension/blob/c934f88f075b0ca71de889923d02db193549902f/background/services/provider-bridge/index.ts#L268 

⚠️ My original assessment was wrong! For the real reason see https://github.com/tallycash/extension/pull/1963#issuecomment-1217990405 ⚠️

### PR DESCRIPTION
**Pull request by mhluongo**
Switching networks in the extension shouldn't impact different dApp connections.

# To Test

- [x] Visit app.uniswap.org and connect to Tally Ho
- [x] Change Tally Ho to Polygon, and make sure Uniswap hasn't switched networks
- [x] Change Tally Ho back to Ethereum, then change Uniswap to Polygon. Ensure the extension is still set to mainnet

Closes #1846

### CODE REVIEW

**Comment by greg-nagy** [comment]
@0xDaedalus @mhluongo have you tested this PR? I am running a test on main after this is merged, and the network is still changing for me. 

The other thing is that this codepath is used only for notifying the dapps about the account change. See the parameters. The network part has been reworked [to use the network that's set for the dApp](https://github.com/tallycash/extension/blob/fdc7daafe442bbd0ee5e4ac00ccaf203c5363a81/background/services/provider-bridge/index.ts#L273)

I know I have suggested this as the source of the problem in the element thread, but I was mistaken.

**Comment by mhluongo** [comment]
Hmmm, I did spend a fair amount of time testing on Uniswap. This patch + refreshing the extension and hard-refreshing the app.uniswap.org got the behavior I believe we want.

Can you give steps to reproduce the issue you're seeing @greg-nagy?

**Comment by mhluongo** [comment]
The underlying belief for me here is that we don't *want* the dApp network **or** account to change when the extension network or account changes. The idea being that dApps have a "switch network" button, and to change account you can disconnect and then reconnect with a new account.

**Comment by 0xDaedalus** [comment]
Excellent find - I think in some ways this is a product question here of "should we support dapps without a switch network button".  They seem to be in the minority as crypto moves more and more towards a multi-network paradigm but it sure would be unfortunate if there was a viral dapp or airdrop that we were unable to support because of this issue.

**Comment by Shadowfiend** [comment]
I think the actual product question is “should we tie our extension's primary network to the dApp's network bidirectionally to deal with dApps without a switch network button”. We can support dApps that don't have a switch network button in a way other than updating the main network the extension displays, for example with a network switcher in the lightning menu. Not saying that's the right thing, just saying there are ways to solve the dApp-without-a-network-switcher problem without ALSO tying the dApp's network to the extension UI's network.

Presumably if the dApp's network is fully attached to the extension UI's network, the extension should also display the network for the dApp in the current foreground tab and window, which might change from tab to tab or window to window. There should never be a scenario where the extension UI's network doesn't match the dApp's expected network (the source of #1895, presumably?).

**Comment by greg-nagy** [comment]
I went ahead and implemented a fix for the original problem. @Shadowfiend 's thoughts are correct and deep, but I think we can also get an answer to this question by trying out this fix and see if we have bug reports. 

The reason I did this is that I felt that dapps without network swithcer are rare, but we will see.

**Pull request merged**
