### PR TITLE
🤘 Forks Out: Use a local mainnet fork

### PR DESCRIPTION
**Pull request by greg-nagy**
This PR has got itself a multi-tiered joke ... :)
- Kinves out wordplay: https://www.imdb.com/title/tt8946378/
- Remove the need to fork out ETH for testing
- let's see the metal forks, because this PR rocks ... 🤘

# Problem

We as dApp devs want a dev environment that walks like mainnet quacks like the mainnet but doesn’t cost gas. So we can develop our dApps in a production-like environment but doesn’t cost us an arm and a leg.

The solution is 2 fold: 
1) create a fork for the mainnet locally 
2) use the most dev-friendly wallet EVER  so I can interact with all the live dApps and contracts, but my own transactions are sent to the forked mainnet.

# Blocker issue 
(Murphy)

The only settings that hardhat fork works — since ~Saturday — if you set the chainId to 1337 -> hosted dApps won’t work if they receive that.

# Workaround

Set fork to have chainId 1337 and implement a kind of “man in the middle” solution in the extension.
let’s replace the chainId in outgoing txs to 1337
modify ethers.js to use the localhost URL when the mainnet is selected

# Setup 

- Start the mainnet fork - terminal 1
  - register an [Alchemy account](https://www.alchemy.com/supernode)
  - `git clone https://github.com/tallycash/mainnet-fork-demo`
  - `cd mainnet-fork-demo`
  - `npm install`
  - `npm start`
  - change the url in `hardhat.config.js`
- setup Tally - terminal 2
  - `git clone https://github.com/tallycash/extension tally`
  - `cd tally`
  - `git checkout fork-demo`
  - // `nvm use`
  - `npm install -g yarn`
  - `yarn install`
  - `yarn start --config-name chrome`
- install tally in chrome
  - create a new profile in chrome
  - go to `chrome://extensions`
  - turn on developer mode (right upper corner)
  - `Load unpacked` (left upperish corner)
  - load tally from `./tally/dist/chrome`
  - import a wallet using this seed phrase `test test test test test test test test test test test junk`
  - go to https://app.uniswap.org/
  - connect you new wallet as injected
  - try to swap (might not succeed for the first time ... probably won't :) )

# Demo
[Recordings and screenshot of usage](https://drive.google.com/drive/u/2/folders/1c2jPRuqPI-wUVgeYJsWebQ_IdTvMtwnG)

### CODE REVIEW

**Comment by Jcauley** [comment]
Thank you for letting me keep learning

**Comment by greg-nagy** [comment]
Hey all. 

I missed a step on stage, but if you follow the instructions in the description you will get a working setup!

CleanShot 2022-02-16 at 14 12 39@2x

**Comment by lodotek** [comment]
Hello, great presentation and thanks for your work!
I am having an issue where when I attempt to perform a swap I can see the wallet pop up for a split second and quickly disappear. Please advise.

```
useWrapCallback.tsx:93 Could not deposit {code: 4001, message: 'The user rejected the request.'}
(anonymous) @ useWrapCallback.tsx:93
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
f @ asyncToGenerator.js:3
u @ asyncToGenerator.js:29
Promise.then (async)
f @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ze @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
_f @ react-dom.production.min.js:100
Ff @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ce @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Cf @ react-dom.production.min.js:105
$t @ react-dom.production.min.js:75
Yt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
fetchBaseQuery.ts:35          GET https://api.uniswap.org/v1/quote?protocols=v2%2Cv3&tokenInAddress=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&tokenInChainId=1&tokenOutAddress=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2&tokenOutChainId=1&amount=69000000000000000000&type=exactIn 400
```

image


Thank you

**Comment by greg-nagy** [comment]
accidently closed this PR. This will continue here: https://github.com/tallycash/extension/pull/1094

**Comment by greg-nagy** [comment]
@lodotek this problem has been fixed since then

**Comment by Jcauley** [comment]
yes

**Comment by EnebeliEmmanuel** [comment]
plss how do i impersonate an account so I can swap

**Comment by EnebeliEmmanuel** [comment]
how do i get 10000 eth

**Pull request closed without merging**
