### PR TITLE
Persist keyrings after removing one.

### LINKED ISSUE #1489: Accounts removed in Tally don't stay removed after app refresh, browser close, etc.
### **Build Info:**
0.13.3

### **Related Ticket/PR**
https://discord.com/channels/808358975287722045/888500174685614090/976124476020391936

### **Reproduction Steps:**

v1 (reported by community):
1. Import or create wallet with password and remove address. Now tally shows welcome UI like fresh downloaded extension.
2. Close/exit your browser & open in next minute.
3. Open tally its showing our step-1 address as "read only" [Q1 :- why this not welcome UI]
4. Tap on add wallet -> create new wallet, needs old password [Q2 why i need old password]
5. New wallet creation done :)
6.  Now its showing 2 active wallets, step-1 wallet becomes read only to active wallet like step-5 wallet without importing seeds [Q3 why this happened]

v2 (reported by Nax)
https://user-images.githubusercontent.com/103908695/168877425-7fb88d74-1555-4fcc-8585-f88219937a22.mov

v3 (reported by me)

1. Have wallet(s) connected to Tally
2. Remove Wallets
3. Refresh Tally on the Extensions page
4. Open Tally.

https://www.awesomescreenshot.com/video/8951615?key=bb5733a79aaf293a3b4dd5ec9507ac3e

### **Expected Result:**

All removed accounts (wallets) should stay removed

### **Actual Result:**
They come back

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Closes #1489 

### To Test
- Follow the steps in #1489 - removed accounts should properly stay removed on browser close & extension update.

### CODE REVIEW

**Comment by jagodarybacka** [comment]
For me it is still showing read only state of the account I've removed after browser restart 😞

**Comment by 0xDaedalus** [comment]
whoops - I didn't see Matt's comment and ended up fixing the accountsToTrack issue in this PR.  I'll go ahead and update the copy as well.

**Comment by jagodarybacka** [comment]
@0xDaedalus 
In this setup:
image
if I remove `Sirius` and reload the extension this account will be back on the list

**Comment by 0xDaedalus** [comment]
Added an unlock prompt when removing an address - unfortunately after unlocking you don't get sent back to the page you were at - but this is the status quo as far as I can tell (same thing happens when you try adding an address while extension is locked) so we can address it in another PR.

**Review by jagodarybacka — DISMISSED** [review]
Works great now 🥇  ✨

**Review by jagodarybacka — APPROVED** [review]
Resolved conflict and retested ✅

**Pull request merged**
