### PR TITLE
🕵️‍♂️ Show me the money: Query all tokens on `tokenRefreshes` alarm

### LINKED ISSUE #1158: Wallet Balances Not Updating
ERC-20 Token and ETH balances are not correctly updating in the application.  It is likely that #1082, #1067, and #1109 are all related to this issue.  This issue is here to coordinate bug-hunting efforts to help us get to the root cause quicker.

# Related issues
- [x] #1067 
- [ ] #1082

### PR DESCRIPTION
**Pull request by greg-nagy**
The asset discovery should happen on new account addition
through the `IndexingService.retrieveTokenBalances()` or
the `ChainService.loadAssetTransfers()`.

At the moment the `ChainService.loadAssetTransfers()` is broken
for an unknown reason and this result in us not picking up any
new tokens, that were not present at the time of adding the new
address.

Querying for all the tokens should not be a costly addition to
out api usage — haven't checked though — but will provide
us a solution for now and a safety net for the future.

## Next steps
- fix the `loadAssetTransfers` flow
- implement [event listener on provider](https://docs.ethers.io/v5/api/providers/provider/#Provider--events) (and move away from polling)

## Test
- import a wallet and send an untracked asset to it from another wallet/address
- wait max 1 minute
- see the new asset appear

Closes #1158 #1082

### CODE REVIEW

**Comment by Shadowfiend** [comment]
This is going to explicitly miss assets the user has (that we've detected through regular transaction enrichment) that aren't on Alchemy's top 100 list (see https://docs.alchemy.com/alchemy/enhanced-apis/token-api/alchemy_gettokenbalances#parameters for what happens if default tokens are used). If we need to go down this path, we need to do active assets AND top-100 assets every time.

**Comment by greg-nagy** [comment]
> explicitly miss assets the user has (that we've detected through regular transaction enrichment)

Currently, this list has 0 elements because of [this bug](https://github.com/tallycash/extension/pull/1746#discussion_r915805696)

I am wondering if it's worth the resources to run 2 API calls and merge their results so we can have a fairly stable safety net.

**Comment by Shadowfiend** [comment]
That bug, though absolutely infuriating, doesn't apply to any transactions initiated from our wallet (swaps or otherwise) that carry ERC20 transfer events picked up by the enrichment service. Though it does explain why we ended up having to add that enrichment pathway to get proper token balances for long tail tokens we were actually broadcasting transactions for 🙃

**Comment by greg-nagy** [comment]
> On the question of whether to do the two calls or something else--I haven't gone deep enough to know for sure. It seems likely we need both if we want decent experience, until we do event/bloom-based detection of all transfers.

I love this so much :) Ty. I was thinking about the same problem, and arrived at the same conclusion!

**Comment by mhluongo** [comment]
I believe this is outdated / good to close —- @greg-nagy can you confirm?

**Comment by greg-nagy** [comment]
The high level idea is still solid although we will take another path on this.

**Pull request closed without merging**
