### PR TITLE
flip da flag for RSK

### LINKED ISSUE #2615: Release RSK (with a `beta` flag)

### PR DESCRIPTION
**Pull request by greg-nagy**
Closes #2615

Latest build: [extension-builds-2538](https://github.com/tallycash/extension/suites/9319259594/artifacts/437773340) (as of Tue, 15 Nov 2022 16:46:36 GMT).

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
How do you feel about undrafting this guy?

**Comment by greg-nagy** [comment]
this is all yours :) I just made this PR to help with QA

feel free to use it however

**Review by 0xDaedalus — APPROVED** [review]
Lets 📈

**Comment by ahsan-javaiid** [comment]
I think flipping RESOLVE_RNS_NAMES will makes sense along with RSK
```
RESOLVE_RNS_NAMES=true
SUPPORT_RSK=true 
```
cc: @alepc253 for confirmation.

**Comment by alepc253** [comment]
Yes, `RNS` name resolution is ready to go too @0xDaedalus @ahsan-javaiid

**Pull request merged**
