### PR TITLE
⛏ Fix persisting custom gas selection

### LINKED ISSUE #1648: Persist Max Miner fee
Custom Max Miner Fee does not get persisted when selected nor does it get persisted between Send ETH screen and confirm ETH transaction screen.

https://github.com/tallycash/extension/pull/1641#issuecomment-1158927866

https://user-images.githubusercontent.com/94649004/174316587-8196ccd4-5b81-4648-85c7-815027402273.mov

### PR DESCRIPTION
**Pull request by henryboldi**
- [x] Uses max priority fee in estimated network fee calculation
- [x] Removes unintentional overrides of the custom gas input

https://user-images.githubusercontent.com/1918798/176006334-b6f093c8-d251-4c75-8b8d-ce228c4cb968.mov

Closes #1648, #1649

### CODE REVIEW

**Comment by greg-nagy** [comment]
I am a bit confused here: Nor #1648 nor #1649 has been fixed in this PR.

I see that this PR fixes some unexpected behavior, but it seems to be detached from the title and the issues.

**Review by greg-nagy — DISMISSED** [review]
@henryboldi should we repurpose this PR so the description matches the work, or do you want to fix the rest of the issues in this PR?

**Comment by henryboldi** [comment]
@greg-nagy For #1649 the estimated network fee is only impacted by the miner fee, so the change is very slight, but that's the intended behavior, no?

**Review by 0xDaedalus — CHANGES_REQUESTED** [review]
I'm still getting the issue present in #1649 

My steps were:

start with `main` build installed
checkout this branch
`USE_CUSTOM_GAS_SELECT=true`
rebuild extension
update chrome extensions
attempt to send eth

https://user-images.githubusercontent.com/94649004/176772869-70f64340-8ccf-4198-9777-9ef11c73b0ee.mov

Preview shows ~50 gwei but minimum base is ~100.

**Review by 0xDaedalus — APPROVED** [review]
Looks like this is working as intended but just supremely confusing - lets get this in and revise (or not) in a future PR.

**Pull request merged**
