### PR TITLE
Reduce number of UNS address lookups

### PR DESCRIPTION
**Pull request by hyphenized**
This PR adds caching to the UNS resolver in an effort to reduce the amount of calls made to the Unstoppable Domains API while syncing blocks.

Refs: 
#1967

- [ ] Watch network requests in the background script, should no longer send requests in burst for the same address

### CODE REVIEW

**Comment by mhluongo** [comment]
Full disclosure, I'm not super familiar with `NameService` so kicking this review to @Shadowfiend. But! Do you know why the generic TTL stuff in `background/services/name/index.ts` didn't cover this @hyphenized?

**Comment by hyphenized** [comment]
@mhluongo I think it's because the UNS lookup methods don't need `chainId` and that's what's being used in the cache strategy at the `NameService`, so it's working but it's making a request in multiple chains for the same address

**Review by jagodarybacka — COMMENTED** [review]
Can we normalize addresses in the cache so addresses with different upper/lowercase letters are pointing to the same cache entry? 
image

**Review by jagodarybacka — APPROVED** [review]
It's a big improvement already so I think address normalization can be added later. I would love to merge it but I would like to hear @0xDaedalus thoughts first :)

**Review by 0xDaedalus — APPROVED** [review]
Code looks fantastic - and I can see requests getting de-duplicated.  📈

**Review by 0xDaedalus — APPROVED** [review]

**Comment by Shadowfiend** [comment]
Btw, I do think having the resolvers cache locally for semantic differences like this is 👌 

I’ll add the flag that we could probably comfortably extend the TTL in this cache to be closer to minutes than seconds. Eventually we probably want to let the resolver communicate back some info to the caller about TTL from the resolver as well. Alternatively, we could push the entire concept of caching onto the resolvers with a couple of helpers to make it easy to do the basics.

**Pull request merged**
