### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [tallycash/wallet](https://hosted.weblate.org/projects/tallycash/wallet/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by gasolin** [comment]
It's an auto push PR generated from weblate 🤩

**Review by jagodarybacka — APPROVED** [review]
Pros: It works! 💖 
Cons: It creates a lot of commits, and I guess that empty file on `zh_Hans` is because there are no entries translated but the language is there. 

Anyway, great job! ✨

**Comment by jagodarybacka** [comment]
@gasolin  We need to somehow provide the linter setup to the weblate 😞

**Comment by gasolin** [comment]
@jagodarybacka there are several addons for weblate 
https://hosted.weblate.org/addons/tallycash/wallet/

add `Squash Git commits` addon seems squash all commits into single one 🤩
removed empty zh_Hans translation

**Comment by jagodarybacka** [comment]
@gasolin can you look for a way to include eslint setup in the weblate? Or if this won't be possible - to disable eslint for these files (but I would like to avoid that)

**Comment by gasolin** [comment]
seems weblate allow customize the output json to 2 spaces intent, lets see how it goes

**Comment by jagodarybacka** [comment]
@gasolin nope, still fails, have you tried 2 spaces or 2 tabs? It seems like to much whitespace

**Review by jagodarybacka — APPROVED** [review]
Let's merge it

**Pull request merged**
