### PR TITLE
🛢 Transaction nonce and gas fixes

### PR DESCRIPTION
**Pull request by jagodarybacka**
This PR is touching multiple issues but they are tightly connected with each other

### What

**Nonce issue**
Ref #2127, #2106 - not closing for now
- Nonce should be released if the transaction failed to broadcast.
This will not fix the problem for users that already have pending or dropped transactions and nonce is in a corrupted state but it will prevent the same issue in the future.

**Gas settings issue**
Ref https://github.com/tallycash/extension/issues/2133 - 90% solved, I see the problem with custom settings - they are losing value, gas limit is ignored.
- We had a problem that the gas settings that the user was changing were not reflected in the transaction. That was because `isEIP1559EnrichedTransactionSignatureRequest(partialRequest)` was expecting `partialRequest` to have `          maxFeePerGas` and `maxPriorityFeePerGas` already set which was never true as this was the function that was supposed to set these values.

**Estimated gwei value issue**
Resolves https://github.com/tallycash/extension/issues/2112 
- Fixed the problem with incorrect gas price calculation - now Optimism and L1 gas calculation logic are not mixed up

### Testing
- setup transaction on any network (all networks should be tested)
- check Estimated network fee button value, compare with current gas prices on given network - they should be similar
- open gas settings panel, change selected option and save
- Estimated network fee should change according to selected gas setting
- set custom, very low gas fee in settings
- sign tx - it should fail to broadcast
- setup another tx, change gas settings and remember what you selected
- sign tx, check it on the scanner website - priority fee and other gas values should be set to the values you selected
- check tx nonce and previous tx nonce - they should be `N` and `N - 1`

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
Can you add testing steps please

**Comment by mhluongo** [comment]
# Potential testing steps

- [ ] Switch to an account on Polygon
- [ ] Attempt to swap on QuickSwap. Set the gas price to anything custom
- [ ] The tx should fail to broadcast. Note the nonce
- [ ] Attempt again to swap on QuickSwap without changing the gas price.
- [ ] It should go through, with the same nonce as the failed tx above

LMK if that's right @jagodarybacka

**Comment by 0xDaedalus** [comment]
Hmmmnn

> The tx should fail to broadcast. Note the nonce

This is not happening for me - quickswap works fine even with gasprice at 0.01 gwei.

**Comment by 0xDaedalus** [comment]
https://github.com/tallycash/extension/issues/2112 could be interfering here

**Comment by jagodarybacka** [comment]
Yup, these are correct testing steps but testing is blocked because of - https://github.com/tallycash/extension/issues/2133 At least for me

**Comment by mhluongo** [comment]
Can we force a tx to fail with a code change, or maybe some other way like trying to spend more of an ERC-20 than we have?

**Comment by jagodarybacka** [comment]
I will just solve the gass issue first

**Comment by 0xDaedalus** [comment]
Gas estimates are not accurate for Optimism:
image

**Comment by jagodarybacka** [comment]
@0xDaedalus hmmm, I can't reproduce such high Optimism gas price
Ethereum:
image
Optimism:
image
Polygon:
image
They all seems fine 🤔

**Pull request merged**
