### PR TITLE
fix: use Tally Ho instead of TallyHo for content

### LINKED ISSUE #1145: Onboard screen 4 mentions TallHo instead of Tally Ho
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On board

### What did not work?

Mixed use of 'Tally Ho' and 'TallyHo'

Screenshot 2022-03-11 at 09 31 08

### Version

Community Edition v0.12.1

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rootial**
## Summary
close #1145 
Simply replace "TallyHo" with "Tally Ho"
## Test
test in local build with firefox
image

## Reviewers
@henryboldi @VladUXUI

### CODE REVIEW

**Comment by rootial** [comment]
image
should we use "Tally Ho" instead of "Tally Ho!" here

**Comment by henryboldi** [comment]
I think  "Tally Ho!" works for titles. We can always adjust that in another PR depending on what @VladUXUI thinks.

**Review by henryboldi — DISMISSED** [review]
👑

**Review by henryboldi — APPROVED** [review]
👑

**Pull request merged**
