### PR TITLE
Fix insufficient balance error overlapping with currency amount

### LINKED ISSUE #2459: ,,Insufficient balance'' message is overlapping on the value in dollars
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Try to send more value than is in the account balance.

### What did not work?

The ,Insufficient balance'' message is overlapping on the value in dollars. 

Screenshot 2022-10-19 at 16 20 58

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hyphenized**
Closes #2459

mypungamehasbeenweaklately

## To Test: 
- [ ] Enter an amount higher than your available balance, the currency amount should no longer display if there's an error

### CODE REVIEW

**Review by jagodarybacka — CHANGES_REQUESTED** [review]
Can you fix the padding/margin so the "send to" field is not moving?

**Comment by hyphenized** [comment]
> Can you fix the padding/margin so the "send to" field is not moving?

Good catch! Should be good now

**Review by 0xDaedalus — APPROVED** [review]
looks 💯 to me

**Review by jagodarybacka — APPROVED** [review]
Looks good ✅

**Comment by Shadowfiend** [comment]
Are we okay with the fact that this means if you have insufficient balance you can't see the balance you do have to adjust accordingly? Cc @VladUXUI

**Pull request merged**
