### PR TITLE
🌐 Network Visibility: Show the current network logo

### LINKED ISSUE #1767: Add network icons to selector
Icons are missing from the selector in the nav:

Screen Shot 2022-07-07 at 9 14 08 PM

Design:
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=10594%3A160108
image

We can use same icons drop full dropdown:
image

### PR DESCRIPTION
**Pull request by mhluongo**
Show the current network's styled square logo in the top menu protocol switcher.

Screenshot from 2022-08-07 12-32-46
Screenshot from 2022-08-07 12-32-38
Screenshot from 2022-08-07 12-32-55

Closes #1767

### CODE REVIEW

**Comment by mhluongo** [comment]
@VladUXUI let me know if that styling checks out, particularly with mainnet

**Comment by jagodarybacka** [comment]
I think it would be nice to make icon change the background to lighter on hover or maybe do something with opacity because it looks weird to me that text is getting brighter but icon stays the same cc @VladUXUI 
image

Also, don't you think that 5px space between icon and text looks better than 3px we have now?
image

**Review by jagodarybacka — DISMISSED** [review]
Code looks good ✨  let's decide what to do about the styles

**Comment by mhluongo** [comment]
Agreed on both fronts, tweaks incoming!

**Comment by mhluongo** [comment]
Let me know how that suits you @jagodarybacka!

**Review by jagodarybacka — APPROVED** [review]
Looks very nice! 🚢

**Pull request merged**
