### PR TITLE
Remove unused HiddenDevPanel component

### PR DESCRIPTION
**Pull request by 0xDaedalus**
This component is defined but not used anywhere in the application.

### CODE REVIEW

**Review by mhluongo — APPROVED** [review]
:hocho: my fav kind of PR

**Comment by hyphenized** [comment]
Maybe we could have a shadowy super doggos panel 🤔

**Comment by greg-nagy** [comment]
I wanted to use that for my not-so-secret runtime enable feature flag idea :( 

Also curious about what could live in the `shadowy super doggos panel` because I just fell in love with this name :)

**Comment by hyphenized** [comment]
Ehhh it's a vague idea, but for example, recently I kept adding the chain service as a global to the window object so I could force the wallet to sync transactions. Though adding to the hidden dev panel some kind of feature to do these common operations did cross my mind, I think in hindsight it would be faster to run these commands in the background page using the console 😄

**Comment by greg-nagy** [comment]
I fell in love with this concept :)

**Pull request merged**
