### PR TITLE
☠️ Remove yearn token list

### PR DESCRIPTION
**Pull request by greg-nagy**
They haven't fixed the SSL isssue for weeks, which is a good signal that it's not maintained properly.

### CODE REVIEW

**Review by henryboldi — APPROVED** [review]
LGTM ✨ but I notice this is in draft mode, so won't merge

**Comment by henryboldi** [comment]
@greg-nagy, is this cool to take out of draft?

**Comment by mhluongo** [comment]
We don't want to delete the list, we want to switch to the new URL.

https://github.com/Uniswap/tokenlists-org/pull/1422

**Comment by mhluongo** [comment]
I suggest we close in favor of https://github.com/tallycash/extension/pull/1613

**Comment by greg-nagy** [comment]
closing in favor of https://github.com/tallycash/extension/pull/1613

**Pull request closed without merging**
