### PR TITLE
Upgrade @ledgerhq

### LINKED ISSUE #2554: Ledger Nano S - Can't set-up a transaction
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Sign a transaction on a Ledger

### What did not work?

**Steps to reproduce:**
- Connect & Unlock Ledger
- Open the Ethereum App on Ledger
- Connect to a dApp with Tally Ho
- Set-up a transaction
Result: Stuck on this screen. Hitting refresh doesn't trigger any action

Screen Shot 2022-11-04 at 07 36 53

**What does a user need to do to fix currently (potentially there's more options ):**
- Disconnect Ledger
- Connect & Unlock Ledger again
- Connect to a dApp with Tally Ho
- Set-up a transaction
- Open the Ethereum App on Ledger
- Hit refresh

Sometimes another fix is 
**Steps to reproduce:**
- Connect & Unlock Ledger
- Open the Ethereum App on Ledger
- Connect to a dApp with Tally Ho
- Set-up a transaction
- Result: Stuck on the refresh screen
- Close & re-open the Ethereum App
- Reject the transaction
- Set it up again

### Version

v0.17.3

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kkosiorowska**
Closes #2554 

This PR Upgrade `@ledgerhq/errors` and `@ledgerhq/hw-app-eth`.  Probably solves the issue of setting up transactions for Ledger Nano S. 

**Issue:**
This issue happens sporadically. When setting up a transaction app is stuck on the below screen. Hitting refresh doesn't trigger any action.

199907775-dc794ce6-6821-4551-97c0-40231679a7ae

## To Test

- [ ] check if the issue still occurs

        Steps to reproduce:
        
        1. Connect & Unlock Ledger
        2. Open the Ethereum App on Ledger
        3. Connect to a dApp with Tally Ho
        4. Set-up a transaction
- [ ] check that the update didn't mess anything up

Latest build: [extension-builds-2697](https://github.com/tallycash/extension/suites/9698136058/artifacts/464706927) (as of Tue, 06 Dec 2022 14:30:12 GMT).

### CODE REVIEW

**Review by jagodarybacka — APPROVED** [review]
I still had a problem - extension claimed that my ledger (Nano S) is not connected but when I closed that slideup and clicked Sign once again it was fine. Next time it was fine too. After reinstall - same thing, first signing has a problem but when you click Sign once again it is ok.

But I think this change shouldn't introduce more errors than we already have. Would be nice to check on another Ledger too.

**Comment by jagodarybacka** [comment]
> How many attempts

Actually one 😄 and then one more to check if after reinstall I have the same problem - I did. If you want we can pair on it later.

**Comment by greg-nagy** [comment]
I have a hunch that the issue comes when the ledger has been connected for the computer for a long time and probably went through a couple of lock-unlock cycle — this might be the reason why it was so easy for @jagodarybacka to reproduce the problem. 

This upgrade doesn't seem to break anything, so let's ship it, and see if the issue happens again.

**Review by greg-nagy — APPROVED** [review]

**Comment by jagodarybacka** [comment]
> ledger has been connected for the computer for a long time 
@greg-nagy nah actually I just connected the ledger after a couple of weeks of not using it. On the other hand, my ledger had weird problems before, maybe that's a hardware problem

**Pull request merged**
