### PR TITLE
Refactor window-provider

### PR DESCRIPTION
**Pull request by hyphenized**
Addresses this TODO:	[window-provider/index.ts:185](https://github.com/tallycash/extension/blob/main/window-provider/index.ts#L185)

## To Test

- [ ] Check that everything works exactly the same

### CODE REVIEW

**Review by greg-nagy — CHANGES_REQUESTED** [review]
hey @hyphenized 

The changes are looking good here! This is an approve on my part. 

I know it's not fair, but this PR is overlapping somewhat with #2460 and that's a priority, so I will ask you to update this PR when that's merged. I am blocking this PR until then.

**Comment by hyphenized** [comment]
No worries, I'll ping you after I update it. Thanks for the review!

**Comment by hyphenized** [comment]
Looks like this wasn't affected by the other PR changes @greg-nagy

**Review by greg-nagy — APPROVED** [review]
let's 🚢

**Pull request merged**
