### PR TITLE
🚨🚓🚨 - Alert on failed transaction broadcasts.

### PR DESCRIPTION
**Pull request by 0xDaedalus**
This PR gets rid of the `transactionSent` event in `chainService` in favor of a try / catch inside of the `broadcastSignedTransaction` event handler that reports a success or failure based on the result of `broadcastSignedTransaction` method in `chainService`.

### Test Criteria
- [ ] A successful transaction should result in a snackbar message of `Transaction signed, broadcasting...`
- [ ] An unsuccessful transaction should result in a snackbar message of `Transaction failed to broadcast.`

The easiest way to simulate an unsuccessful transaction is to edit the code and throw an error inside of `broadcastSignedTransaction`

This PR addresses [an excellent suggestion](https://github.com/tallycash/extension/pull/1201#discussion_r831486778) made in #1201

### CODE REVIEW

**Review by Shadowfiend — DISMISSED** [review]
Yus and yussss let's do it :rocket:

**Comment by Shadowfiend** [comment]
Okay, so unfortunately I just gave swaps a test drive, and a couple of things stood out:
- When a swap transaction completes, it goes to the wallet page, but not to the activity tab :(
- The snackbar message doesn't seem to show up on swap transaction failure.

I ran out of ETH in my test account before I could test swap transaction success snackbar 😅

Also of note, I did see success + failure snackbar messages when doing simple ETH transfers.

**Comment by 0xDaedalus** [comment]
> When a swap transaction completes, it goes to the wallet page, but not to the activity tab :(

I agree that this makes sense but I didn't add it in #1201 because it does not match what is in figma.  I can go ahead and make another issue for that.

> The snackbar message doesn't seem to show up on swap transaction failure

:sadface: looking into this now

**Comment by Shadowfiend** [comment]
> I can go ahead and make another issue for that and address immediately.

Maybe let's hold there and check in with @VladUXUI in chat in the morning, I might have invented the behavior 😅

**Comment by 0xDaedalus** [comment]
Ok so, the issue is that we also call `broadcastSignedTransaction` [here](https://github.com/tallycash/extension/blob/main/background/services/internal-ethereum-provider/index.ts#L170) which is outside of the try/catch block on the `transactionConstructionSliceEmitter` message handler.  I wasn't aware of this other use but its not a problem on `main` since we set the snackbar based on an emit from `broadcastSignedTransaction` regardless of what context it is called in.

In light of this do you think it makes sense to go back to the event based pattern and simply add alerting for failed transactions as part of this enhancement?

**Comment by Shadowfiend** [comment]
Yep, 100% agree and feel a little silly for having forgotten it 😅

**Comment by 0xDaedalus** [comment]
Closed in favor of #1250

**Pull request closed without merging**
