### PR TITLE
v0.13.3

### PR DESCRIPTION
**Pull request by greg-nagy**
✨✨✨

- UNS name resolution
- Performance improvements

✨✨✨

## What's Changed
* v0.13.2 by @greg-nagy in https://github.com/tallycash/extension/pull/1365
* 💚 Update `SharedButton` default text color to dark green by @henryboldi in https://github.com/tallycash/extension/pull/1370
* ✍️ Contract interaction sign page by @henryboldi in https://github.com/tallycash/extension/pull/1371
* Uns uns uns: Turn on UNS resolution feature by @Shadowfiend in https://github.com/tallycash/extension/pull/1375
* 🥦 Prune asset prices older than a day from Redux store by @henryboldi in https://github.com/tallycash/extension/pull/1376
* The Man With No Name 🤠 by @0xDaedalus in https://github.com/tallycash/extension/pull/1373
* Create SharedAccordion component by @jagodarybacka in https://github.com/tallycash/extension/pull/1372
* 🎚 Add "Set Tally Ho as default" toggle to set password page by @henryboldi in https://github.com/tallycash/extension/pull/1378
* Hocus Focus: Implement focus and disabled styling for SharedInput and seed phrase input by @Shadowfiend in https://github.com/tallycash/extension/pull/1377
* 🫓 Fuckin' NaN: Fix long-tail token price bug by @mhluongo in https://github.com/tallycash/extension/pull/1388
* 😊 The future is optimistic: Refactor ChainService to support Arbitrum and Optimism by @mhluongo in https://github.com/tallycash/extension/pull/1355
* 🐶📦 Pack the dogs: Add docker build for identical outputs by @greg-nagy in https://github.com/tallycash/extension/pull/1374
* 🥗 Resolve CPU issues from `blocks` bloat in Redux store by @henryboldi in https://github.com/tallycash/extension/pull/1363

**Full Changelog**: https://github.com/tallycash/extension/compare/v0.13.2...v0.13.3

### CODE REVIEW

**Comment by henryboldi** [comment]
😁💪

**Comment by SJQuality** [comment]
QA approved. No blocking issues.

**Review by SJQuality — COMMENTED** [review]
QA approved. No blocking issues.

**Review by SJQuality — APPROVED** [review]
QA approved. No blocking issues.

**Pull request merged**
