### PR TITLE
Update Tally Tokenlist

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Closes https://github.com/tallycash/extension/issues/1730

### To Test
- Reinstall Tally
- There should be more than 10 polygon swap pairs
- the ipfs uri should match the [`build token lists for main`](https://github.com/tallycash/token-list/runs/7240322358?check_suite_focus=true) output in the token-list repo.

### CODE REVIEW

**Comment by mhluongo** [comment]
Let's say you don't reinstall Tally, and instead just upgrade in place. Will you still see the new tokens? I suspect you won't without some sort of upgrade.

**Comment by 0xDaedalus** [comment]
> Let's say you don't reinstall Tally, and instead just upgrade in place. Will you still see the new tokens? I suspect you won't without some sort of upgrade.

It should be refreshed after a minute as part of `handleTokenAlarm`

**Comment by mhluongo** [comment]
Wallets before this PR will have the old token list URL in their default preferences, though, not the new one. I'll test to confirm

**Comment by 0xDaedalus** [comment]
Ah if thats the case I must have misunderstood @Shadowfiend's comment in slack - happy to test and fix if we find that an upgrade is needed

**Comment by mhluongo** [comment]
Did a build from `main`, loaded an account, waited, then screenshotted the token list preferences. Then rebuilt and refreshed the extension. Screenshots below — not they both include the old URL.

Screenshot from 2022-07-08 17-48-50
Screenshot from 2022-07-08 17-44-19

**Review by mhluongo — APPROVED** [review]
Very nice 👌

**Pull request merged**
