### PR TITLE
Change z-index for account options menu on the accounts panel

### LINKED ISSUE #1957: Layering issue on the accounts panel with account options menu
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/1008118952804765768

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

UI issue on accounts panel where you view all addresses when you have multiple addresses.

### What did not work?

Option menu background appears underneath the dots of the row after it

image

### Version

Community Edition v0.14.3

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kkosiorowska**
Closes #1957 

This PR fixes layering issue on the accounts panel. Option menu background appears underneath the dots of the row after it. The z-index property has been changed which specifies the stack order of an element. 

**Before:**
Screenshot 2022-08-24 at 09 05 08

**After:**
Screenshot 2022-08-24 at 09 07 16

**To Test** 
- [ ] Go to accounts panel and attempt to open account options when have multiple addresses.

### CODE REVIEW

**Comment by jagodarybacka** [comment]
you need to verify and sign your commits so your commits will have 'verified' badge 😄 https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
image

**Comment by 0xDaedalus** [comment]
Lets also link back to the issue that references this PR.  If you prepend it with `Closes` that issue will automatically close once this PR is merged.

**Comment by jagodarybacka** [comment]
@0xDaedalus she did it manually I guess because it is linked but yeah, with "closes" or "resolves" keywords it's easier https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by mhluongo** [comment]
A few more notes on the PR

* Please include a description! Even in the one-liners like this.
* In UI-related PRs, screenshots of new behavior are always appreciated.
* Please include steps to test. We manually QR every PR that gets merged, test instructions and screenshots go a long way. [Here's a good example](https://github.com/tallycash/extension/pull/2001) from @0xDaedalus

**Comment by kkosiorowska** [comment]
This PR fixes layering issue on the accounts panel. Option menu background appears underneath the dots of the row after it. The z-index property has been changed which specifies the stack order of an element. 

**Before:**
Screenshot 2022-08-24 at 09 05 08

**After:**
Screenshot 2022-08-24 at 09 07 16

**To Test** 
- [ ] Go to accounts panel and attempt to open account options when have multiple addresses.

**Review by jagodarybacka — APPROVED** [review]
Looks good ✨

**Pull request merged**
