### PR TITLE
🤘 Scroll Lotta Love

### LINKED ISSUE #339: Fix scroll bars in Firefox
ROUNDED CORNERS
^ From @itsrachelfish

### LINKED ISSUE #771: Make `SharedSlideUpMenu` scrollable
What in tarnation! What a bunch of malarkey!

scroll hell

### LINKED ISSUE #778: Snackbar sometimes not clearing when extension closed before display duration
### Discord Discussion Link

hen copying an address the 'Copied' pop-up closes like it should. But when it's still present and you close the extension and re-opens the pop-up is still there. Seems like the counter stops when the extension is minimised. I think the pop-up should close when the extension is minimised and not pop-up again when re-opening 

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Copy an address from the receive page

### What did not work?

> Minor: When copying an address the 'Copied' pop-up closes like it should. But when it's still present and you close the extension and re-opens the pop-up is still there. Seems like the counter stops when the extension is minimised. I think the pop-up should close when the extension is minimised and not pop-up again when re-opening

– @Naxsun

### Version

Community Edition v0.9.1

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by henryboldi**
> “Whole Lotta Love” might have gotten the band sued by Willie Dixon, but there was no sonic precedent for it in rock music—it’s a sound that would have been unimaginable without the rise of drug culture.

This PR includes fixes for,

- [x] Unwanted scroll bars in Firefox (Closes #339)
- [x] Super janky scroll in the account switcher (Closes #771)
- [x] The `Snackbar` sticking around if the extension is closed before `Snackbar` disappears (Closes #778)

### CODE REVIEW

**Comment by mhluongo** [comment]
Is this the intended visual behavior for the account switcher? Seems like that bar should be at the bottom...?

Screenshot from 2021-12-30 15-13-57

While I'm at it, I also expected clicking the account avatar once would open the switcher, and a second time would close it. Probably outside the scope of this PR but didn't want to lose it

**Comment by henryboldi** [comment]
Definitely not! One sec

**Comment by henryboldi** [comment]
> Seems like that bar should be at the bottom...?

Definitely. Thank you for catching this 😬. How's it looking now?

<br/>

> While I'm at it, I also expected clicking the account avatar once would open the switcher, and a second time would close it. 

Good point! Fixed and included here https://github.com/tallycash/extension/pull/780/commits/3d6236dc190903a5027d1ff13b952933d2b52164

**Review by mhluongo — APPROVED** [review]
Bellisimo

**Pull request merged**
