### PR TITLE
Optimistically Named Router: Add 0x and Uniswap contract names on Opti and Arbi

### PR DESCRIPTION
**Pull request by mhluongo**
The beauty of ✨ CREATE2 ✨ means the same address works across networks for both contracts.

# To Test

- [ ] Do an in-wallet swap on Optimism. You should see the contract name "0x Router"

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
The address is different on optimism unfortunately:

https://optimistic.etherscan.io/address/0xdef1abe32c034e558cdd535791643c58a13acc10

**Comment by mhluongo** [comment]
Oh noo, they deployed both on Optimism! Thanks for catching that

**Comment by 0xDaedalus** [comment]
We should really change that `network` property to `networks` - I'll make an issue

**Comment by mhluongo** [comment]
Updated and ready for another look

**Review by 0xDaedalus — APPROVED** [review]
👑

**Pull request merged**
